src/liberio.c: munmap ALL buffers on channel free
EttusResearch/liberio pull request #1
Opened 2019-03-26 21:15 UTC by a-will

A bug in the loop freeing resources caused the 0th buffer to remain
mapped to the user process. This fixes that issue.

Signed-off-by: Alex Williams <alex.williams@ni.com>

2019-03-26 23:23 UTC, mbr0wn approved these changes

2019-03-26 23:30 UTC, vkakade commented
How do we explain the non-deterministic (race condition like) nature of the original bug?https://github.com/EttusResearch/uhddev/issues/3206
Did kernel panic depend on whether or not we were freeing valid memory?

2019-03-26 23:36 UTC, mbr0wn commented
My hunch is the garbage pointer. A garbage pointer can be such that it doesn't crash, it just does nothing.

2019-03-27 03:01 UTC, mfischer requested changes
Good catch! Can you update Makefile.am with libtool version?

2019-05-06 21:50 UTC, a-will commented
@mfischer Updated the version numbers. Now pkg-config will give the correct info too.

2019-05-06 23:03 UTC, mfischer commented
Applied to master.

2019-05-06 23:03 UTC, closed without merging